// 組み込み関数の引数の数の表を、DirectXShaderCompiler の gen_intrin_main.txt から作る。
//
// 使い方 (リポジトリのルートで):
//   node tools/intrinsics/generate.mjs
//
// 固定したコミットの gen_intrin_main.txt を取得し、
// src/Shaderlyn.Semantics/Symbols/HlslIntrinsicArity.g.cs を書き出す。
// 解析の実行時には何も取得しない。表は生成済みのファイルとしてリポジトリに入る。
//
// gen_intrin_main.txt は University of Illinois/NCSA Open Source License で配布されている。
// 生成したファイルの先頭にその旨と著作権表示を入れる (tools/intrinsics/LICENSE-DXC.txt)。

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const Commit = '52e290027dda8158080beb069aa8114998d66b5c';
const SourceUrl =
  `https://raw.githubusercontent.com/microsoft/DirectXShaderCompiler/${Commit}/utils/hct/gen_intrin_main.txt`;

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const output = join(root, 'src', 'Shaderlyn.Semantics', 'Symbols', 'HlslIntrinsicArity.g.cs');

const response = await fetch(SourceUrl);
if (!response.ok) {
  throw new Error(`取得できませんでした: ${response.status} ${SourceUrl}`);
}

const text = await response.text();

/** 名前ごとの、受け付ける引数の数。variadic は「その数以上」。 */
const functions = new Map();

let namespace = null;

for (const rawLine of text.split(/\r?\n/)) {
  const line = rawLine.replace(/\/\/.*$/, '').trim();

  if (line.length === 0) {
    continue;
  }

  const start = /^namespace\s+(\w+)\s*\{/.exec(line);
  if (start) {
    namespace = start[1];
    continue;
  }

  if (line.startsWith('}')) {
    namespace = null;
    continue;
  }

  // 関数形式の組み込み関数だけを扱う。メソッドは受け取る側の型が要るので別に扱う。
  if (namespace !== 'Intrinsics') {
    continue;
  }

  const declaration = /(\w+)\s*\((.*)\)\s*(?::\s*\w+\s*)?;$/.exec(line);
  if (!declaration) {
    throw new Error(`読めない行です: ${rawLine}`);
  }

  const [, name, parameterText] = declaration;
  const parameters = splitTopLevel(parameterText);
  const variadic = parameters.length > 0 && parameters[parameters.length - 1] === '...';
  const count = variadic ? parameters.length - 1 : parameters.length;

  const entry = functions.get(name) ?? { counts: new Set(), variadicFrom: null };
  entry.counts.add(count);
  if (variadic) {
    entry.variadicFrom = entry.variadicFrom === null ? count : Math.min(entry.variadicFrom, count);
  }
  functions.set(name, entry);
}

/** 山括弧の中のカンマでは分けずに、引数の並びを分ける。 */
function splitTopLevel(parameterText) {
  const result = [];
  let depth = 0;
  let current = '';

  for (const c of parameterText) {
    if (c === '<') depth++;
    if (c === '>') depth--;
    if (c === ',' && depth === 0) {
      result.push(current.trim());
      current = '';
      continue;
    }
    current += c;
  }

  if (current.trim().length > 0) {
    result.push(current.trim());
  }

  return result;
}

const names = [...functions.keys()].sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));

const rows = names.map((name) => {
  const { counts, variadicFrom } = functions.get(name);
  const sorted = [...counts].sort((a, b) => a - b).join(', ');
  const variadic = variadicFrom === null ? '-1' : String(variadicFrom);
  return `        ["${name}"] = new([${sorted}], ${variadic}),`;
});

const generated = `// <auto-generated>
// tools/intrinsics/generate.mjs が生成した。手で書き換えないこと。
//
// 元のデータ: DirectXShaderCompiler の utils/hct/gen_intrin_main.txt (コミット ${Commit})
// Copyright (C) Microsoft Corporation. All rights reserved.
// University of Illinois/NCSA Open Source License で配布されている。
// 条文は tools/intrinsics/LICENSE-DXC.txt にある。
// </auto-generated>

using System.Collections.Frozen;

namespace Shaderlyn.Semantics.Symbols;

/// <summary>組み込み関数が受け付ける引数の数。</summary>
/// <param name="Counts">多重定義ごとの引数の数。</param>
/// <param name="VariadicFrom">この数以上ならいくつでも受け付ける。可変長でなければ -1。</param>
public readonly record struct IntrinsicArity(int[] Counts, int VariadicFrom)
{
    /// <summary>その数の引数を受け付けるかを判定する。</summary>
    /// <param name="count">引数の数。</param>
    /// <returns>受け付けるなら <see langword="true"/>。</returns>
    public bool Accepts(int count) => Array.IndexOf(Counts, count) >= 0 || (VariadicFrom >= 0 && count >= VariadicFrom);
}

/// <summary>組み込み関数の引数の数の表。</summary>
public static partial class HlslIntrinsicArity
{
    /// <summary>名前から、受け付ける引数の数への対応。</summary>
    public static FrozenDictionary<string, IntrinsicArity> Functions { get; } =
        new Dictionary<string, IntrinsicArity>(StringComparer.Ordinal)
    {
${rows.join('\n')}
    }.ToFrozenDictionary(StringComparer.Ordinal);
}
`;

writeFileSync(output, generated.replace(/\n/g, '\r\n'));
console.log(`${names.length} 個の組み込み関数を書き出しました: ${output}`);
